const ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  ORG_ADMIN: "ORGANIZATION_ADMIN",
  MANAGER: "MANAGER", // MANAGER
  HR: "HUMAN_RESOURCE", //HR
  EMPLOYEE: "EMPLOYEE", // USER
});

export default ROLES;
