const ROLES = Object.freeze({
    SUPER_ADMIN: "SUPER_ADMIN",
    ORG_ADMIN: "ORGANIZATION_ADMIN",
    MANAGER: "MANAGER",
    HR: "HUMAN_RECOURSE",
    EMPLOYEE: "EMPLOYEE"
});

export default ROLES;