module.exports = Object.freeze({
    ANNOUNCEMENT: "ANNOUNCEMENT",
    BIRTHDAY: "BIRTHDAY",
    SYSTEM: "SYSTEM",
    WORK_ANNIVERSARY: "WORK_ANNIVERSARY",
    LEAVE_REQUEST: "LEAVE_REQUEST",
    LEAVE_APPROVED: "LEAVE_APPROVED",
    LEAVE_REJECTED: "LEAVE_REJECTED",
    TASK_ASSIGNED: "TASK_ASSIGNED",

});